title: Rajanie Prabha
position: Machine Learning Research Scientist
affiliation: Pittsburgh Supercomputing Center, Carnegie Mellon University
email: rajanie.prabha (at) gmail.com
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=Qd84JgEAAAAJ&hl=en
github_link: https://github.com/rajanieprabha
linkedin: https://www.linkedin.com/in/rajanieprabha
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: I eat while my model trains.
canonical: https://rajanieprabha.github.io
remote_theme: yaoyao-liu/minimal-light
